"""add api_keys and user_default_models

Revision ID: 0ae6b35ef59c
Revises: 425cd5ccf52a
Create Date: 2026-03-06 01:28:51.265208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae6b35ef59c'
down_revision: Union[str, Sequence[str], None] = '425cd5ccf52a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_id', name='uq_user_provider_key')
    )
    op.create_index(op.f('ix_api_keys_provider_id'), 'api_keys', ['provider_id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('user_default_models',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('llm_model_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'llm_model_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_default_models')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_provider_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
