"""add index on llm_models provider_id

Revision ID: 1804062098cc
Revises: b026dd15a505
Create Date: 2026-03-04 23:35:01.849386

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1804062098cc'
down_revision: str | Sequence[str] | None = 'b026dd15a505'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_llm_models_provider_id'), 'llm_models', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_models_provider_id'), table_name='llm_models')
    # ### end Alembic commands ###
