"""add structured columns to llm_calls

Revision ID: 5d4430a49477
Revises: 1aa31ef3a43f
Create Date: 2026-03-06 23:24:12.809482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4430a49477'
down_revision: Union[str, Sequence[str], None] = '1aa31ef3a43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_calls', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('llm_calls', sa.Column('key_points', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('llm_calls', sa.Column('has_disagreements', sa.Boolean(), nullable=True))
    op.add_column('llm_calls', sa.Column('disagreements', sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_calls', 'disagreements')
    op.drop_column('llm_calls', 'has_disagreements')
    op.drop_column('llm_calls', 'key_points')
    op.drop_column('llm_calls', 'confidence')
    # ### end Alembic commands ###
