"""add summarizer_model_id to user_settings

Revision ID: 8a4ac0743e64
Revises: d9d545447940
Create Date: 2026-03-06 12:00:41.878002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4ac0743e64'
down_revision: Union[str, Sequence[str], None] = 'd9d545447940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('summarizer_model_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_user_settings_summarizer_model_id', 'user_settings', 'llm_models', ['summarizer_model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_settings_summarizer_model_id', 'user_settings', type_='foreignkey')
    op.drop_column('user_settings', 'summarizer_model_id')
    # ### end Alembic commands ###
